### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by michalsrutek**

### CODE REVIEW

**Comment by olejnjak** [comment]
Hello thanks for your interest, but this is not a typo 🙂 see https://www.grammarly.com/blog/its-vs-its/ 🙂

**Comment by janmisar** [comment]
@olejnjak According to your link (and also my knowledge btw), @michalsrutek is right I think 🤔😄

**Comment by olejnjak** [comment]
Two verbs in a single sentence like really?

**Comment by janmisar** [comment]
Maybe I’m confused 😄 but the suggestion is “its” and now we have “it’s” so current version is wrong, isn’t it..?

**Comment by olejnjak** [comment]
yayks my bad 🙈

**Comment by michalsrutek** [comment]
No worries, that's what PRs are for :D

**Comment by olejnjak** [comment]
Either way please @michalsrutek add your entry to changelog so we can merge your PR 🙂

**Comment by michalsrutek** [comment]
Thanks, @olejnjak. Pushed the change. Is it alright now?

**Comment by olejnjak** [comment]
Yes, seems fine 🙂 Thanks for you contribution 🙂

**Pull request merged**
