### PR TITLE
Ios deployment

### PR DESCRIPTION
**Pull request by freed0m266**
#### Checklist
- [ ] Added tests (if applicable)

### CODE REVIEW

**Comment by olejnjak** [comment]
Hi, what is the motivation here, I don't see a single reason here for increasing deployment target to 14.0. 12.0 is acceptable as that is the lowest supported by Xcode 15.x

**Comment by freed0m266** [comment]
Hi 👋 My motivation was just a warning in projects where I'm using ACKategories, that's all. 🙂

**Comment by olejnjak** [comment]
Well then iOS 12 is the way to go as it is the lowest supported version in Xcode 15 and we also need iOS for some of our projects.

**Comment by babacros** [comment]
@freed0m266  Hey, you can just create a fork for this purpose.

**Comment by olejnjak** [comment]
In #137 I bumped deployment target to iOS 12, so this should be solved.

**Pull request closed without merging**
