### PR TITLE
Make public functions open 

### PR DESCRIPTION
**Pull request by janmisar**
...to enable overrides in subclasses

#### Checklist
- [ ] Added tests (if applicable)

### CODE REVIEW

**Comment by LukasHromadnik** [comment]
I would personally make all those methods `open`. It's gonna be easier in future for us to debug some weird behaviors.

What do you think?

**Comment by janmisar** [comment]
> I would personally make all those methods `open`. It's gonna be easier in future for us to debug some weird behaviors.
> 
> What do you think?

You mean that `UINavigationControllerDelegate` method? Or even add/removeChild? 🤔

**Comment by LukasHromadnik** [comment]
I would open everything 😄 you never know

**Comment by janmisar** [comment]
True.. I don't see the reason not to do it 🤷‍♂️

**Review by LukasHromadnik — APPROVED** [review]
Finally somebody did that. Thanks!

**Pull request merged**
